CREATE TABLE DIM_DATE (
	DATE_ID INT IDENTITY PRIMARY KEY,
	DAY_HOUSE INT,
	MONTH_HOUSE INT,
	QUARTER_HOUSE SMALLINT,
	YEAR_HOUSE INT,
	WEEK_OF_YEAR INT,
	DAY_OF_WEEK INT 
) 


SELECT * FROM DIM_DATE


CREATE TABLE DIM_LEGAL_DOCUMENTS (
	PAPERS_ID INT IDENTITY PRIMARY KEY,
	PAPERS NVARCHAR(255)
)

SELECT * FROM DIM_LEGAL_DOCUMENTS


CREATE TABLE LOCATION_HOUSE (
	LOCATION_ID INT IDENTITY PRIMARY KEY,
	ROAD NVARCHAR(555),
	WARD NVARCHAR(255),
	DISTRICT NVARCHAR(255),
	PROVINCE NVARCHAR(6)
)


CREATE TABLE DIM_HOUSE (
	HOUSE_ID INT IDENTITY PRIMARY KEY ,
	TYPE_OF_HOUSING NVARCHAR(255),
	NUMBER_OF_FLOORS INT,
	NUMBER_OF_BEDROOMS SMALLINT,
)



CREATE TABLE FACT (
    FACT_ID INT IDENTITY PRIMARY KEY,
	Area float,
    Price float,
    Long float,
    Width float,
    DATE_ID int,
    PAPERS_ID int,
    HOUSE_ID int,
	LOCATION_ID INT
)

SELECT* FROM FACT 


ALTER TABLE DIM_HOUSE 
ADD CONSTRAINT LOCATION_ID_fk FOREIGN KEY (LOCATION_ID)
REFERENCES LOCATION_HOUSE(LOCATION_ID)

ALTER TABLE fact 
DROP CONSTRAINT  HOUSE_ID_fk ;


ALTER TABLE FACT
ADD CONSTRAINT HOUSE_ID_fk FOREIGN KEY (HOUSE_ID)
REFERENCES DIM_HOUSE(HOUSE_ID)

ALTER TABLE FACT
ADD CONSTRAINT PAPERS_ID_fk FOREIGN KEY (PAPERS_ID)
REFERENCES DIM_LEGAL_DOCUMENTS(PAPERS_ID)

ALTER TABLE FACT
ADD CONSTRAINT DATE_ID_fk FOREIGN KEY (DATE_ID)
REFERENCES DIM_DATE(DATE_ID)




